module.exports = {
  reject: [
    "@openzeppelin/contracts-v4",
    "@openzeppelin/contracts-upgradeable-v4",
    "@react-native-async-storage/async-storage",
    "@types/react",
    "@typescript-eslint/eslint-plugin",
    "@typescript-eslint/parser",
    "account-abstraction",
    "eslint",
    "expo-build-properties",
    "expo-clipboard",
    "expo-constants",
    "expo-font",
    "expo-linking",
    "expo-router",
    "expo-status-bar",
    "react",
    "react-dom",
    "react-native",
    "react-native-reanimated",
    "react-native-safe-area-context",
    "react-native-screens",
    "react-native-svg",
    "react-native-webview",
    "sharp-cli",
  ],
};
