module.exports = {
  reject: [
    "@react-native-async-storage/async-storage",
    "@types/react",
    "eslint",
    "expo-application",
    "expo-build-properties",
    "expo-constants",
    "expo-device",
    "expo-font",
    "expo-linking",
    "expo-router",
    "expo-splash-screen",
    "expo-sqlite",
    "expo-status-bar",
    "expo-system-ui",
    "expo-web-browser",
    "react",
    "react-dom",
    "react-native",
    "react-native-gesture-handler",
    "react-native-safe-area-context",
    "react-native-screens",
    "sharp-cli",
    "typescript",
  ],
};
