auditConfig:
  ignoreGhsas: # cspell:ignore ghsas
    - GHSA-28wg-ghj8-5hjv
    - GHSA-2v37-7h3g-55p8
    - GHSA-395f-4hp3-45gv
    - GHSA-4x5r-pxfx-6jf8 # cspell:ignore pxfx
    - GHSA-52cp-r559-cp3m
    - GHSA-5p4m-2wfm-xmqj # cspell:ignore xmqj
    - GHSA-6g55-p6wh-862q
    - GHSA-848j-6mx2-7j84
    - GHSA-866g-f22w-33x8
    - GHSA-fxqj-rqcc-2cmp # cspell:ignore fxqj rqcc
    - GHSA-h67p-54hq-rp68
    - GHSA-5p2g-fcmc-qvqq # cspell:ignore fcmc qvqq
    - GHSA-mh99-v99m-4gvg
    - GHSA-r28c-9q8g-f849
    - GHSA-rgw5-rvv9-x895
    - GHSA-vcc3-ghjq-m6fr # cspell:ignore ghjq
    - GHSA-w3rx-r6r6-pgpr # cspell:ignore pgpr
    - GHSA-w5hq-g745-h8pq
autoInstallPeers: false
catalog:
  "@aa-sdk/core": &aaSDK ^4.86.1
  "@account-kit/infra": *aaSDK
  "@account-kit/smart-contracts": *aaSDK
  eslint: &eslint ^9.39.4
  "@eslint/js": *eslint
  "@hono/node-server": ^2.0.12
  nx: &nx ^23.1.1
  "@nx/esbuild": *nx
  "@nx/eslint": *nx
  "@nx/eslint-plugin": *nx
  "@nx/js": *nx
  "@sentry/core": &sentry ^10.71.0
  "@sentry/node": *sentry
  "@sentry/profiling-node": *sentry
  tamagui: &tamagui ^1.144.4
  "@tamagui/animations-moti": *tamagui
  "@tamagui/babel-plugin": *tamagui
  "@tamagui/config": *tamagui
  "@tamagui/lucide-icons": *tamagui
  "@tamagui/toast": *tamagui
  "@wagmi/core": ^3.4.1
  hono: ^4.13.5
  i18next: ^26.0.5
  ioredis: ^5.10.1
  ox: ^0.14.7
  react: &react "19.2.0"
  react-dom: *react
  typescript: ^5.9.3
  valibot: ^1.4.2
  viem: ^2.47.6
  wagmi: ^3.6.0
ignoreWorkspaceRootCheck: true
includeWorkspaceRoot: true
minimumReleaseAge: 1440
packages:
  - "."
  - common
  - contracts
  - docs
  - infra
  - server
  - substreams
  - .maestro
publicHoistPattern:
  - "@babel/runtime"
  - "@react-native/assets-registry"
  - "@react-native/gradle-plugin"
  - "@sentry/cli"
  - expo-asset
  - expo-modules-autolinking
  - react-native-web
  - sharp
