encryptionsalt: v1::v1:AAAAAAAAAAAAAAAb:rYjVO7/uF2+Qv1LhWq5c2S0ZR4rZaQ==
config:
  gcp:project: exa-dev
  exa:subscribeTimeout: 600s
  exa:whatsappPhoneNumberId: "1287864854409817"
  exa:personaBusinessAccountTypeId: acttp_AWN3X1Rb7Rnt5o7EA4e8VcU7D61xH2
